// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,json_types=true"
// @generated from file auth/v1/auth.proto (package auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import type { User, UserJson, UserSchema } from "../../common/v1/common_pb";
import { file_common_v1_common } from "../../common/v1/common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file auth/v1/auth.proto.
 */
export const file_auth_v1_auth: GenFile = /*@__PURE__*/
  fileDesc("ChJhdXRoL3YxL2F1dGgucHJvdG8SB2F1dGgudjEiPgoNU2lnblVwUmVxdWVzdBINCgVlbWFpbBgBIAEoCRIMCgRuYW1lGAIgASgJEhAKCHBhc3N3b3JkGAMgASgJIi8KDExvZ0luUmVxdWVzdBINCgVlbWFpbBgBIAEoCRIQCghwYXNzd29yZBgCIAEoCSI8CgxBdXRoUmVzcG9uc2USHQoEdXNlchgBIAEoCzIPLmNvbW1vbi52MS5Vc2VyEg0KBXRva2VuGAIgASgJIj4KFFVwZGF0ZVByb2ZpbGVSZXF1ZXN0EgwKBG5hbWUYASABKAkSGAoQZGVmYXVsdF9jdXJyZW5jeRgCIAEoCTKqAgoLQXV0aFNlcnZpY2USNwoGU2lnblVwEhYuYXV0aC52MS5TaWduVXBSZXF1ZXN0GhUuYXV0aC52MS5BdXRoUmVzcG9uc2USNQoFTG9nSW4SFS5hdXRoLnYxLkxvZ0luUmVxdWVzdBoVLmF1dGgudjEuQXV0aFJlc3BvbnNlEjgKBkxvZ091dBIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRIwCgVHZXRNZRIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRoPLmNvbW1vbi52MS5Vc2VyEj8KDVVwZGF0ZVByb2ZpbGUSHS5hdXRoLnYxLlVwZGF0ZVByb2ZpbGVSZXF1ZXN0Gg8uY29tbW9uLnYxLlVzZXJiBnByb3RvMw", [file_google_protobuf_empty, file_common_v1_common]);

/**
 * @generated from message auth.v1.SignUpRequest
 */
export type SignUpRequest = Message<"auth.v1.SignUpRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string password = 3;
   */
  password: string;
};

/**
 * @generated from message auth.v1.SignUpRequest
 */
export type SignUpRequestJson = {
  /**
   * @generated from field: string email = 1;
   */
  email?: string;

  /**
   * @generated from field: string name = 2;
   */
  name?: string;

  /**
   * @generated from field: string password = 3;
   */
  password?: string;
};

/**
 * Describes the message auth.v1.SignUpRequest.
 * Use `create(SignUpRequestSchema)` to create a new message.
 */
export const SignUpRequestSchema: GenMessage<SignUpRequest, {jsonType: SignUpRequestJson}> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 0);

/**
 * @generated from message auth.v1.LogInRequest
 */
export type LogInRequest = Message<"auth.v1.LogInRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * @generated from message auth.v1.LogInRequest
 */
export type LogInRequestJson = {
  /**
   * @generated from field: string email = 1;
   */
  email?: string;

  /**
   * @generated from field: string password = 2;
   */
  password?: string;
};

/**
 * Describes the message auth.v1.LogInRequest.
 * Use `create(LogInRequestSchema)` to create a new message.
 */
export const LogInRequestSchema: GenMessage<LogInRequest, {jsonType: LogInRequestJson}> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 1);

/**
 * @generated from message auth.v1.AuthResponse
 */
export type AuthResponse = Message<"auth.v1.AuthResponse"> & {
  /**
   * @generated from field: common.v1.User user = 1;
   */
  user?: User | undefined;

  /**
   * Bearer token; pass as "Authorization: Bearer <token>" on future calls.
   *
   * @generated from field: string token = 2;
   */
  token: string;
};

/**
 * @generated from message auth.v1.AuthResponse
 */
export type AuthResponseJson = {
  /**
   * @generated from field: common.v1.User user = 1;
   */
  user?: UserJson;

  /**
   * Bearer token; pass as "Authorization: Bearer <token>" on future calls.
   *
   * @generated from field: string token = 2;
   */
  token?: string;
};

/**
 * Describes the message auth.v1.AuthResponse.
 * Use `create(AuthResponseSchema)` to create a new message.
 */
export const AuthResponseSchema: GenMessage<AuthResponse, {jsonType: AuthResponseJson}> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 2);

/**
 * @generated from message auth.v1.UpdateProfileRequest
 */
export type UpdateProfileRequest = Message<"auth.v1.UpdateProfileRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string default_currency = 2;
   */
  defaultCurrency: string;
};

/**
 * @generated from message auth.v1.UpdateProfileRequest
 */
export type UpdateProfileRequestJson = {
  /**
   * @generated from field: string name = 1;
   */
  name?: string;

  /**
   * @generated from field: string default_currency = 2;
   */
  defaultCurrency?: string;
};

/**
 * Describes the message auth.v1.UpdateProfileRequest.
 * Use `create(UpdateProfileRequestSchema)` to create a new message.
 */
export const UpdateProfileRequestSchema: GenMessage<UpdateProfileRequest, {jsonType: UpdateProfileRequestJson}> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 3);

/**
 * Email + password auth. LogIn/SignUp return a bearer token for mobile
 * clients and additionally set an httpOnly session cookie for browsers.
 *
 * @generated from service auth.v1.AuthService
 */
export const AuthService: GenService<{
  /**
   * @generated from rpc auth.v1.AuthService.SignUp
   */
  signUp: {
    methodKind: "unary";
    input: typeof SignUpRequestSchema;
    output: typeof AuthResponseSchema;
  },
  /**
   * @generated from rpc auth.v1.AuthService.LogIn
   */
  logIn: {
    methodKind: "unary";
    input: typeof LogInRequestSchema;
    output: typeof AuthResponseSchema;
  },
  /**
   * @generated from rpc auth.v1.AuthService.LogOut
   */
  logOut: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc auth.v1.AuthService.GetMe
   */
  getMe: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof UserSchema;
  },
  /**
   * @generated from rpc auth.v1.AuthService.UpdateProfile
   */
  updateProfile: {
    methodKind: "unary";
    input: typeof UpdateProfileRequestSchema;
    output: typeof UserSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_auth_v1_auth, 0);

