// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,json_types=true"
// @generated from file receipt/v1/receipt.proto (package receipt.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file receipt/v1/receipt.proto.
 */
export const file_receipt_v1_receipt: GenFile = /*@__PURE__*/
  fileDesc("ChhyZWNlaXB0L3YxL3JlY2VpcHQucHJvdG8SCnJlY2VpcHQudjEiOAoTUGFyc2VSZWNlaXB0UmVxdWVzdBINCgVpbWFnZRgBIAEoDBISCgptZWRpYV90eXBlGAIgASgJImIKEVBhcnNlZFJlY2VpcHRJdGVtEgwKBG5hbWUYASABKAkSEAoIcXVhbnRpdHkYAiABKAUSGAoQdW5pdF9wcmljZV9jZW50cxgDIAEoBRITCgt0b3RhbF9jZW50cxgEIAEoBSLCAQoNUGFyc2VkUmVjZWlwdBIQCghtZXJjaGFudBgBIAEoCRIMCgRkYXRlGAIgASgJEhAKCGN1cnJlbmN5GAMgASgJEiwKBWl0ZW1zGAQgAygLMh0ucmVjZWlwdC52MS5QYXJzZWRSZWNlaXB0SXRlbRIWCg5zdWJ0b3RhbF9jZW50cxgFIAEoBRIRCgl0YXhfY2VudHMYBiABKAUSEQoJdGlwX2NlbnRzGAcgASgFEhMKC3RvdGFsX2NlbnRzGAggASgFIlQKFFBhcnNlUmVjZWlwdFJlc3BvbnNlEioKB3JlY2VpcHQYASABKAsyGS5yZWNlaXB0LnYxLlBhcnNlZFJlY2VpcHQSEAoIcHJvdmlkZXIYAiABKAkyYwoOUmVjZWlwdFNlcnZpY2USUQoMUGFyc2VSZWNlaXB0Eh8ucmVjZWlwdC52MS5QYXJzZVJlY2VpcHRSZXF1ZXN0GiAucmVjZWlwdC52MS5QYXJzZVJlY2VpcHRSZXNwb25zZWIGcHJvdG8z");

/**
 * @generated from message receipt.v1.ParseReceiptRequest
 */
export type ParseReceiptRequest = Message<"receipt.v1.ParseReceiptRequest"> & {
  /**
   * @generated from field: bytes image = 1;
   */
  image: Uint8Array;

  /**
   * image/jpeg | image/png | image/webp | image/gif
   *
   * @generated from field: string media_type = 2;
   */
  mediaType: string;
};

/**
 * @generated from message receipt.v1.ParseReceiptRequest
 */
export type ParseReceiptRequestJson = {
  /**
   * @generated from field: bytes image = 1;
   */
  image?: string;

  /**
   * image/jpeg | image/png | image/webp | image/gif
   *
   * @generated from field: string media_type = 2;
   */
  mediaType?: string;
};

/**
 * Describes the message receipt.v1.ParseReceiptRequest.
 * Use `create(ParseReceiptRequestSchema)` to create a new message.
 */
export const ParseReceiptRequestSchema: GenMessage<ParseReceiptRequest, {jsonType: ParseReceiptRequestJson}> = /*@__PURE__*/
  messageDesc(file_receipt_v1_receipt, 0);

/**
 * @generated from message receipt.v1.ParsedReceiptItem
 */
export type ParsedReceiptItem = Message<"receipt.v1.ParsedReceiptItem"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: int32 quantity = 2;
   */
  quantity: number;

  /**
   * @generated from field: int32 unit_price_cents = 3;
   */
  unitPriceCents: number;

  /**
   * @generated from field: int32 total_cents = 4;
   */
  totalCents: number;
};

/**
 * @generated from message receipt.v1.ParsedReceiptItem
 */
export type ParsedReceiptItemJson = {
  /**
   * @generated from field: string name = 1;
   */
  name?: string;

  /**
   * @generated from field: int32 quantity = 2;
   */
  quantity?: number;

  /**
   * @generated from field: int32 unit_price_cents = 3;
   */
  unitPriceCents?: number;

  /**
   * @generated from field: int32 total_cents = 4;
   */
  totalCents?: number;
};

/**
 * Describes the message receipt.v1.ParsedReceiptItem.
 * Use `create(ParsedReceiptItemSchema)` to create a new message.
 */
export const ParsedReceiptItemSchema: GenMessage<ParsedReceiptItem, {jsonType: ParsedReceiptItemJson}> = /*@__PURE__*/
  messageDesc(file_receipt_v1_receipt, 1);

/**
 * @generated from message receipt.v1.ParsedReceipt
 */
export type ParsedReceipt = Message<"receipt.v1.ParsedReceipt"> & {
  /**
   * @generated from field: string merchant = 1;
   */
  merchant: string;

  /**
   * YYYY-MM-DD or empty
   *
   * @generated from field: string date = 2;
   */
  date: string;

  /**
   * @generated from field: string currency = 3;
   */
  currency: string;

  /**
   * @generated from field: repeated receipt.v1.ParsedReceiptItem items = 4;
   */
  items: ParsedReceiptItem[];

  /**
   * @generated from field: int32 subtotal_cents = 5;
   */
  subtotalCents: number;

  /**
   * @generated from field: int32 tax_cents = 6;
   */
  taxCents: number;

  /**
   * @generated from field: int32 tip_cents = 7;
   */
  tipCents: number;

  /**
   * @generated from field: int32 total_cents = 8;
   */
  totalCents: number;
};

/**
 * @generated from message receipt.v1.ParsedReceipt
 */
export type ParsedReceiptJson = {
  /**
   * @generated from field: string merchant = 1;
   */
  merchant?: string;

  /**
   * YYYY-MM-DD or empty
   *
   * @generated from field: string date = 2;
   */
  date?: string;

  /**
   * @generated from field: string currency = 3;
   */
  currency?: string;

  /**
   * @generated from field: repeated receipt.v1.ParsedReceiptItem items = 4;
   */
  items?: ParsedReceiptItemJson[];

  /**
   * @generated from field: int32 subtotal_cents = 5;
   */
  subtotalCents?: number;

  /**
   * @generated from field: int32 tax_cents = 6;
   */
  taxCents?: number;

  /**
   * @generated from field: int32 tip_cents = 7;
   */
  tipCents?: number;

  /**
   * @generated from field: int32 total_cents = 8;
   */
  totalCents?: number;
};

/**
 * Describes the message receipt.v1.ParsedReceipt.
 * Use `create(ParsedReceiptSchema)` to create a new message.
 */
export const ParsedReceiptSchema: GenMessage<ParsedReceipt, {jsonType: ParsedReceiptJson}> = /*@__PURE__*/
  messageDesc(file_receipt_v1_receipt, 2);

/**
 * @generated from message receipt.v1.ParseReceiptResponse
 */
export type ParseReceiptResponse = Message<"receipt.v1.ParseReceiptResponse"> & {
  /**
   * @generated from field: receipt.v1.ParsedReceipt receipt = 1;
   */
  receipt?: ParsedReceipt | undefined;

  /**
   * Which provider produced the result: "local" | "anthropic" | "mock".
   *
   * @generated from field: string provider = 2;
   */
  provider: string;
};

/**
 * @generated from message receipt.v1.ParseReceiptResponse
 */
export type ParseReceiptResponseJson = {
  /**
   * @generated from field: receipt.v1.ParsedReceipt receipt = 1;
   */
  receipt?: ParsedReceiptJson;

  /**
   * Which provider produced the result: "local" | "anthropic" | "mock".
   *
   * @generated from field: string provider = 2;
   */
  provider?: string;
};

/**
 * Describes the message receipt.v1.ParseReceiptResponse.
 * Use `create(ParseReceiptResponseSchema)` to create a new message.
 */
export const ParseReceiptResponseSchema: GenMessage<ParseReceiptResponse, {jsonType: ParseReceiptResponseJson}> = /*@__PURE__*/
  messageDesc(file_receipt_v1_receipt, 3);

/**
 * AI receipt itemization. The server tries configured providers in order
 * (self-hosted vision box, cloud API, mock) and returns a normalized draft
 * that the user reviews before it becomes an itemized expense — AI output
 * is never auto-committed.
 *
 * @generated from service receipt.v1.ReceiptService
 */
export const ReceiptService: GenService<{
  /**
   * @generated from rpc receipt.v1.ReceiptService.ParseReceipt
   */
  parseReceipt: {
    methodKind: "unary";
    input: typeof ParseReceiptRequestSchema;
    output: typeof ParseReceiptResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_receipt_v1_receipt, 0);

