// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,json_types=true"
// @generated from file social/v1/social.proto (package social.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import type { CounterpartyBalance, CounterpartyBalanceJson, User, UserJson, UserSchema } from "../../common/v1/common_pb";
import { file_common_v1_common } from "../../common/v1/common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file social/v1/social.proto.
 */
export const file_social_v1_social: GenFile = /*@__PURE__*/
  fileDesc("ChZzb2NpYWwvdjEvc29jaWFsLnByb3RvEglzb2NpYWwudjEiLwoQQWRkRnJpZW5kUmVxdWVzdBINCgVlbWFpbBgBIAEoCRIMCgRuYW1lGAIgASgJIkYKE0xpc3RGcmllbmRzUmVzcG9uc2USLwoHZnJpZW5kcxgBIAMoCzIeLmNvbW1vbi52MS5Db3VudGVycGFydHlCYWxhbmNlIicKE0xpc3RBY3Rpdml0eVJlcXVlc3QSEAoIZ3JvdXBfaWQYASABKAkijgEKDUFjdGl2aXR5RXZlbnQSCgoCaWQYASABKAkSEAoIZ3JvdXBfaWQYAiABKAkSHgoFYWN0b3IYAyABKAsyDy5jb21tb24udjEuVXNlchIMCgR0eXBlGAQgASgJEg8KB21lc3NhZ2UYBSABKAkSDAoEbGluaxgGIAEoCRISCgpjcmVhdGVkX2F0GAcgASgJIkAKFExpc3RBY3Rpdml0eVJlc3BvbnNlEigKBmV2ZW50cxgBIAMoCzIYLnNvY2lhbC52MS5BY3Rpdml0eUV2ZW50InUKDE5vdGlmaWNhdGlvbhIKCgJpZBgBIAEoCRIMCgR0eXBlGAIgASgJEg0KBXRpdGxlGAMgASgJEgwKBGJvZHkYBCABKAkSDAoEbGluaxgFIAEoCRIMCgRyZWFkGAYgASgIEhIKCmNyZWF0ZWRfYXQYByABKAkiYQoZTGlzdE5vdGlmaWNhdGlvbnNSZXNwb25zZRIuCg1ub3RpZmljYXRpb25zGAEgAygLMhcuc29jaWFsLnYxLk5vdGlmaWNhdGlvbhIUCgx1bnJlYWRfY291bnQYAiABKAUy/gIKDVNvY2lhbFNlcnZpY2USOQoJQWRkRnJpZW5kEhsuc29jaWFsLnYxLkFkZEZyaWVuZFJlcXVlc3QaDy5jb21tb24udjEuVXNlchJFCgtMaXN0RnJpZW5kcxIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRoeLnNvY2lhbC52MS5MaXN0RnJpZW5kc1Jlc3BvbnNlEk8KDExpc3RBY3Rpdml0eRIeLnNvY2lhbC52MS5MaXN0QWN0aXZpdHlSZXF1ZXN0Gh8uc29jaWFsLnYxLkxpc3RBY3Rpdml0eVJlc3BvbnNlElEKEUxpc3ROb3RpZmljYXRpb25zEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GiQuc29jaWFsLnYxLkxpc3ROb3RpZmljYXRpb25zUmVzcG9uc2USRwoVTWFya05vdGlmaWNhdGlvbnNSZWFkEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5YgZwcm90bzM", [file_google_protobuf_empty, file_common_v1_common]);

/**
 * @generated from message social.v1.AddFriendRequest
 */
export type AddFriendRequest = Message<"social.v1.AddFriendRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * optional display name for shadow users
   *
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * @generated from message social.v1.AddFriendRequest
 */
export type AddFriendRequestJson = {
  /**
   * @generated from field: string email = 1;
   */
  email?: string;

  /**
   * optional display name for shadow users
   *
   * @generated from field: string name = 2;
   */
  name?: string;
};

/**
 * Describes the message social.v1.AddFriendRequest.
 * Use `create(AddFriendRequestSchema)` to create a new message.
 */
export const AddFriendRequestSchema: GenMessage<AddFriendRequest, {jsonType: AddFriendRequestJson}> = /*@__PURE__*/
  messageDesc(file_social_v1_social, 0);

/**
 * @generated from message social.v1.ListFriendsResponse
 */
export type ListFriendsResponse = Message<"social.v1.ListFriendsResponse"> & {
  /**
   * @generated from field: repeated common.v1.CounterpartyBalance friends = 1;
   */
  friends: CounterpartyBalance[];
};

/**
 * @generated from message social.v1.ListFriendsResponse
 */
export type ListFriendsResponseJson = {
  /**
   * @generated from field: repeated common.v1.CounterpartyBalance friends = 1;
   */
  friends?: CounterpartyBalanceJson[];
};

/**
 * Describes the message social.v1.ListFriendsResponse.
 * Use `create(ListFriendsResponseSchema)` to create a new message.
 */
export const ListFriendsResponseSchema: GenMessage<ListFriendsResponse, {jsonType: ListFriendsResponseJson}> = /*@__PURE__*/
  messageDesc(file_social_v1_social, 1);

/**
 * @generated from message social.v1.ListActivityRequest
 */
export type ListActivityRequest = Message<"social.v1.ListActivityRequest"> & {
  /**
   * empty = everything visible to the caller
   *
   * @generated from field: string group_id = 1;
   */
  groupId: string;
};

/**
 * @generated from message social.v1.ListActivityRequest
 */
export type ListActivityRequestJson = {
  /**
   * empty = everything visible to the caller
   *
   * @generated from field: string group_id = 1;
   */
  groupId?: string;
};

/**
 * Describes the message social.v1.ListActivityRequest.
 * Use `create(ListActivityRequestSchema)` to create a new message.
 */
export const ListActivityRequestSchema: GenMessage<ListActivityRequest, {jsonType: ListActivityRequestJson}> = /*@__PURE__*/
  messageDesc(file_social_v1_social, 2);

/**
 * @generated from message social.v1.ActivityEvent
 */
export type ActivityEvent = Message<"social.v1.ActivityEvent"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string group_id = 2;
   */
  groupId: string;

  /**
   * @generated from field: common.v1.User actor = 3;
   */
  actor?: User | undefined;

  /**
   * expense_added | expense_deleted | settlement | member_added | group_created | comment
   *
   * @generated from field: string type = 4;
   */
  type: string;

  /**
   * pre-rendered, human-readable
   *
   * @generated from field: string message = 5;
   */
  message: string;

  /**
   * app path, e.g. /expenses/<id>
   *
   * @generated from field: string link = 6;
   */
  link: string;

  /**
   * @generated from field: string created_at = 7;
   */
  createdAt: string;
};

/**
 * @generated from message social.v1.ActivityEvent
 */
export type ActivityEventJson = {
  /**
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * @generated from field: string group_id = 2;
   */
  groupId?: string;

  /**
   * @generated from field: common.v1.User actor = 3;
   */
  actor?: UserJson;

  /**
   * expense_added | expense_deleted | settlement | member_added | group_created | comment
   *
   * @generated from field: string type = 4;
   */
  type?: string;

  /**
   * pre-rendered, human-readable
   *
   * @generated from field: string message = 5;
   */
  message?: string;

  /**
   * app path, e.g. /expenses/<id>
   *
   * @generated from field: string link = 6;
   */
  link?: string;

  /**
   * @generated from field: string created_at = 7;
   */
  createdAt?: string;
};

/**
 * Describes the message social.v1.ActivityEvent.
 * Use `create(ActivityEventSchema)` to create a new message.
 */
export const ActivityEventSchema: GenMessage<ActivityEvent, {jsonType: ActivityEventJson}> = /*@__PURE__*/
  messageDesc(file_social_v1_social, 3);

/**
 * @generated from message social.v1.ListActivityResponse
 */
export type ListActivityResponse = Message<"social.v1.ListActivityResponse"> & {
  /**
   * @generated from field: repeated social.v1.ActivityEvent events = 1;
   */
  events: ActivityEvent[];
};

/**
 * @generated from message social.v1.ListActivityResponse
 */
export type ListActivityResponseJson = {
  /**
   * @generated from field: repeated social.v1.ActivityEvent events = 1;
   */
  events?: ActivityEventJson[];
};

/**
 * Describes the message social.v1.ListActivityResponse.
 * Use `create(ListActivityResponseSchema)` to create a new message.
 */
export const ListActivityResponseSchema: GenMessage<ListActivityResponse, {jsonType: ListActivityResponseJson}> = /*@__PURE__*/
  messageDesc(file_social_v1_social, 4);

/**
 * @generated from message social.v1.Notification
 */
export type Notification = Message<"social.v1.Notification"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string type = 2;
   */
  type: string;

  /**
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * @generated from field: string body = 4;
   */
  body: string;

  /**
   * @generated from field: string link = 5;
   */
  link: string;

  /**
   * @generated from field: bool read = 6;
   */
  read: boolean;

  /**
   * @generated from field: string created_at = 7;
   */
  createdAt: string;
};

/**
 * @generated from message social.v1.Notification
 */
export type NotificationJson = {
  /**
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * @generated from field: string type = 2;
   */
  type?: string;

  /**
   * @generated from field: string title = 3;
   */
  title?: string;

  /**
   * @generated from field: string body = 4;
   */
  body?: string;

  /**
   * @generated from field: string link = 5;
   */
  link?: string;

  /**
   * @generated from field: bool read = 6;
   */
  read?: boolean;

  /**
   * @generated from field: string created_at = 7;
   */
  createdAt?: string;
};

/**
 * Describes the message social.v1.Notification.
 * Use `create(NotificationSchema)` to create a new message.
 */
export const NotificationSchema: GenMessage<Notification, {jsonType: NotificationJson}> = /*@__PURE__*/
  messageDesc(file_social_v1_social, 5);

/**
 * @generated from message social.v1.ListNotificationsResponse
 */
export type ListNotificationsResponse = Message<"social.v1.ListNotificationsResponse"> & {
  /**
   * @generated from field: repeated social.v1.Notification notifications = 1;
   */
  notifications: Notification[];

  /**
   * @generated from field: int32 unread_count = 2;
   */
  unreadCount: number;
};

/**
 * @generated from message social.v1.ListNotificationsResponse
 */
export type ListNotificationsResponseJson = {
  /**
   * @generated from field: repeated social.v1.Notification notifications = 1;
   */
  notifications?: NotificationJson[];

  /**
   * @generated from field: int32 unread_count = 2;
   */
  unreadCount?: number;
};

/**
 * Describes the message social.v1.ListNotificationsResponse.
 * Use `create(ListNotificationsResponseSchema)` to create a new message.
 */
export const ListNotificationsResponseSchema: GenMessage<ListNotificationsResponse, {jsonType: ListNotificationsResponseJson}> = /*@__PURE__*/
  messageDesc(file_social_v1_social, 6);

/**
 * Friends, the activity feed and in-app notifications.
 *
 * @generated from service social.v1.SocialService
 */
export const SocialService: GenService<{
  /**
   * Add a friend by email; creates a claimable shadow user if needed.
   *
   * @generated from rpc social.v1.SocialService.AddFriend
   */
  addFriend: {
    methodKind: "unary";
    input: typeof AddFriendRequestSchema;
    output: typeof UserSchema;
  },
  /**
   * @generated from rpc social.v1.SocialService.ListFriends
   */
  listFriends: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof ListFriendsResponseSchema;
  },
  /**
   * @generated from rpc social.v1.SocialService.ListActivity
   */
  listActivity: {
    methodKind: "unary";
    input: typeof ListActivityRequestSchema;
    output: typeof ListActivityResponseSchema;
  },
  /**
   * @generated from rpc social.v1.SocialService.ListNotifications
   */
  listNotifications: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof ListNotificationsResponseSchema;
  },
  /**
   * @generated from rpc social.v1.SocialService.MarkNotificationsRead
   */
  markNotificationsRead: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof EmptySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_social_v1_social, 0);

