// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,json_types=true"
// @generated from file common/v1/common.proto (package common.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common/v1/common.proto.
 */
export const file_common_v1_common: GenFile = /*@__PURE__*/
  fileDesc("ChZjb21tb24vdjEvY29tbW9uLnByb3RvEgljb21tb24udjEicwoEVXNlchIKCgJpZBgBIAEoCRINCgVlbWFpbBgCIAEoCRIMCgRuYW1lGAMgASgJEhQKDGF2YXRhcl9jb2xvchgEIAEoCRIYChBkZWZhdWx0X2N1cnJlbmN5GAUgASgJEhIKCnJlZ2lzdGVyZWQYBiABKAgiRgoERGVidBIUCgxmcm9tX3VzZXJfaWQYASABKAkSEgoKdG9fdXNlcl9pZBgCIAEoCRIUCgxhbW91bnRfY2VudHMYAyABKAUiMAoKTmV0QmFsYW5jZRIPCgd1c2VyX2lkGAEgASgJEhEKCW5ldF9jZW50cxgCIAEoBSJHChNDb3VudGVycGFydHlCYWxhbmNlEh0KBHVzZXIYASABKAsyDy5jb21tb24udjEuVXNlchIRCgluZXRfY2VudHMYAiABKAViBnByb3RvMw");

/**
 * A person. Users may be "shadow" users (invited by email, not yet
 * registered) — they participate in expenses like anyone else and claim
 * the account by signing up with the same email.
 *
 * @generated from message common.v1.User
 */
export type User = Message<"common.v1.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * Deterministic accent color used for the avatar, e.g. "#0f8a5f".
   *
   * @generated from field: string avatar_color = 4;
   */
  avatarColor: string;

  /**
   * ISO 4217 code, e.g. "USD", "BDT".
   *
   * @generated from field: string default_currency = 5;
   */
  defaultCurrency: string;

  /**
   * @generated from field: bool registered = 6;
   */
  registered: boolean;
};

/**
 * A person. Users may be "shadow" users (invited by email, not yet
 * registered) — they participate in expenses like anyone else and claim
 * the account by signing up with the same email.
 *
 * @generated from message common.v1.User
 */
export type UserJson = {
  /**
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * @generated from field: string email = 2;
   */
  email?: string;

  /**
   * @generated from field: string name = 3;
   */
  name?: string;

  /**
   * Deterministic accent color used for the avatar, e.g. "#0f8a5f".
   *
   * @generated from field: string avatar_color = 4;
   */
  avatarColor?: string;

  /**
   * ISO 4217 code, e.g. "USD", "BDT".
   *
   * @generated from field: string default_currency = 5;
   */
  defaultCurrency?: string;

  /**
   * @generated from field: bool registered = 6;
   */
  registered?: boolean;
};

/**
 * Describes the message common.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User, {jsonType: UserJson}> = /*@__PURE__*/
  messageDesc(file_common_v1_common, 0);

/**
 * A pairwise debt: `from_user_id` owes `to_user_id`.
 *
 * @generated from message common.v1.Debt
 */
export type Debt = Message<"common.v1.Debt"> & {
  /**
   * @generated from field: string from_user_id = 1;
   */
  fromUserId: string;

  /**
   * @generated from field: string to_user_id = 2;
   */
  toUserId: string;

  /**
   * @generated from field: int32 amount_cents = 3;
   */
  amountCents: number;
};

/**
 * A pairwise debt: `from_user_id` owes `to_user_id`.
 *
 * @generated from message common.v1.Debt
 */
export type DebtJson = {
  /**
   * @generated from field: string from_user_id = 1;
   */
  fromUserId?: string;

  /**
   * @generated from field: string to_user_id = 2;
   */
  toUserId?: string;

  /**
   * @generated from field: int32 amount_cents = 3;
   */
  amountCents?: number;
};

/**
 * Describes the message common.v1.Debt.
 * Use `create(DebtSchema)` to create a new message.
 */
export const DebtSchema: GenMessage<Debt, {jsonType: DebtJson}> = /*@__PURE__*/
  messageDesc(file_common_v1_common, 1);

/**
 * A user's net position: positive = they are owed, negative = they owe.
 *
 * @generated from message common.v1.NetBalance
 */
export type NetBalance = Message<"common.v1.NetBalance"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: int32 net_cents = 2;
   */
  netCents: number;
};

/**
 * A user's net position: positive = they are owed, negative = they owe.
 *
 * @generated from message common.v1.NetBalance
 */
export type NetBalanceJson = {
  /**
   * @generated from field: string user_id = 1;
   */
  userId?: string;

  /**
   * @generated from field: int32 net_cents = 2;
   */
  netCents?: number;
};

/**
 * Describes the message common.v1.NetBalance.
 * Use `create(NetBalanceSchema)` to create a new message.
 */
export const NetBalanceSchema: GenMessage<NetBalance, {jsonType: NetBalanceJson}> = /*@__PURE__*/
  messageDesc(file_common_v1_common, 2);

/**
 * Overall position against one person across groups and one-off expenses.
 * net_cents > 0 means they owe you.
 *
 * @generated from message common.v1.CounterpartyBalance
 */
export type CounterpartyBalance = Message<"common.v1.CounterpartyBalance"> & {
  /**
   * @generated from field: common.v1.User user = 1;
   */
  user?: User | undefined;

  /**
   * @generated from field: int32 net_cents = 2;
   */
  netCents: number;
};

/**
 * Overall position against one person across groups and one-off expenses.
 * net_cents > 0 means they owe you.
 *
 * @generated from message common.v1.CounterpartyBalance
 */
export type CounterpartyBalanceJson = {
  /**
   * @generated from field: common.v1.User user = 1;
   */
  user?: UserJson;

  /**
   * @generated from field: int32 net_cents = 2;
   */
  netCents?: number;
};

/**
 * Describes the message common.v1.CounterpartyBalance.
 * Use `create(CounterpartyBalanceSchema)` to create a new message.
 */
export const CounterpartyBalanceSchema: GenMessage<CounterpartyBalance, {jsonType: CounterpartyBalanceJson}> = /*@__PURE__*/
  messageDesc(file_common_v1_common, 3);

