// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,json_types=true"
// @generated from file group/v1/group.proto (package group.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import type { User, UserJson } from "../../common/v1/common_pb";
import { file_common_v1_common } from "../../common/v1/common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file group/v1/group.proto.
 */
export const file_group_v1_group: GenFile = /*@__PURE__*/
  fileDesc("ChRncm91cC92MS9ncm91cC5wcm90bxIIZ3JvdXAudjEiNQoGTWVtYmVyEh0KBHVzZXIYASABKAsyDy5jb21tb24udjEuVXNlchIMCgRyb2xlGAIgASgJIowBCgVHcm91cBIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEgwKBHR5cGUYAyABKAkSEAoIY3VycmVuY3kYBCABKAkSEgoKY3JlYXRlZF9ieRgFIAEoCRISCgpjcmVhdGVkX2F0GAYgASgJEiEKB21lbWJlcnMYByADKAsyEC5ncm91cC52MS5NZW1iZXIiQgoSQ3JlYXRlR3JvdXBSZXF1ZXN0EgwKBG5hbWUYASABKAkSDAoEdHlwZRgCIAEoCRIQCghjdXJyZW5jeRgDIAEoCSJcCgxHcm91cFN1bW1hcnkSHgoFZ3JvdXAYASABKAsyDy5ncm91cC52MS5Hcm91cBIUCgxtZW1iZXJfY291bnQYAiABKAUSFgoOeW91cl9uZXRfY2VudHMYAyABKAUiPAoSTGlzdEdyb3Vwc1Jlc3BvbnNlEiYKBmdyb3VwcxgBIAMoCzIWLmdyb3VwLnYxLkdyb3VwU3VtbWFyeSIjCg9HZXRHcm91cFJlcXVlc3QSEAoIZ3JvdXBfaWQYASABKAkiQQoQQWRkTWVtYmVyUmVxdWVzdBIQCghncm91cF9pZBgBIAEoCRINCgVlbWFpbBgCIAEoCRIMCgRuYW1lGAMgASgJIjgKE1JlbW92ZU1lbWJlclJlcXVlc3QSEAoIZ3JvdXBfaWQYASABKAkSDwoHdXNlcl9pZBgCIAEoCTLKAgoMR3JvdXBTZXJ2aWNlEjwKC0NyZWF0ZUdyb3VwEhwuZ3JvdXAudjEuQ3JlYXRlR3JvdXBSZXF1ZXN0Gg8uZ3JvdXAudjEuR3JvdXASQgoKTGlzdEdyb3VwcxIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRocLmdyb3VwLnYxLkxpc3RHcm91cHNSZXNwb25zZRI2CghHZXRHcm91cBIZLmdyb3VwLnYxLkdldEdyb3VwUmVxdWVzdBoPLmdyb3VwLnYxLkdyb3VwEjkKCUFkZE1lbWJlchIaLmdyb3VwLnYxLkFkZE1lbWJlclJlcXVlc3QaEC5ncm91cC52MS5NZW1iZXISRQoMUmVtb3ZlTWVtYmVyEh0uZ3JvdXAudjEuUmVtb3ZlTWVtYmVyUmVxdWVzdBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eWIGcHJvdG8z", [file_google_protobuf_empty, file_common_v1_common]);

/**
 * @generated from message group.v1.Member
 */
export type Member = Message<"group.v1.Member"> & {
  /**
   * @generated from field: common.v1.User user = 1;
   */
  user?: User | undefined;

  /**
   * "owner" | "member"
   *
   * @generated from field: string role = 2;
   */
  role: string;
};

/**
 * @generated from message group.v1.Member
 */
export type MemberJson = {
  /**
   * @generated from field: common.v1.User user = 1;
   */
  user?: UserJson;

  /**
   * "owner" | "member"
   *
   * @generated from field: string role = 2;
   */
  role?: string;
};

/**
 * Describes the message group.v1.Member.
 * Use `create(MemberSchema)` to create a new message.
 */
export const MemberSchema: GenMessage<Member, {jsonType: MemberJson}> = /*@__PURE__*/
  messageDesc(file_group_v1_group, 0);

/**
 * @generated from message group.v1.Group
 */
export type Group = Message<"group.v1.Group"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * "trip" | "home" | "couple" | "other"
   *
   * @generated from field: string type = 3;
   */
  type: string;

  /**
   * @generated from field: string currency = 4;
   */
  currency: string;

  /**
   * @generated from field: string created_by = 5;
   */
  createdBy: string;

  /**
   * @generated from field: string created_at = 6;
   */
  createdAt: string;

  /**
   * @generated from field: repeated group.v1.Member members = 7;
   */
  members: Member[];
};

/**
 * @generated from message group.v1.Group
 */
export type GroupJson = {
  /**
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * @generated from field: string name = 2;
   */
  name?: string;

  /**
   * "trip" | "home" | "couple" | "other"
   *
   * @generated from field: string type = 3;
   */
  type?: string;

  /**
   * @generated from field: string currency = 4;
   */
  currency?: string;

  /**
   * @generated from field: string created_by = 5;
   */
  createdBy?: string;

  /**
   * @generated from field: string created_at = 6;
   */
  createdAt?: string;

  /**
   * @generated from field: repeated group.v1.Member members = 7;
   */
  members?: MemberJson[];
};

/**
 * Describes the message group.v1.Group.
 * Use `create(GroupSchema)` to create a new message.
 */
export const GroupSchema: GenMessage<Group, {jsonType: GroupJson}> = /*@__PURE__*/
  messageDesc(file_group_v1_group, 1);

/**
 * @generated from message group.v1.CreateGroupRequest
 */
export type CreateGroupRequest = Message<"group.v1.CreateGroupRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string type = 2;
   */
  type: string;

  /**
   * @generated from field: string currency = 3;
   */
  currency: string;
};

/**
 * @generated from message group.v1.CreateGroupRequest
 */
export type CreateGroupRequestJson = {
  /**
   * @generated from field: string name = 1;
   */
  name?: string;

  /**
   * @generated from field: string type = 2;
   */
  type?: string;

  /**
   * @generated from field: string currency = 3;
   */
  currency?: string;
};

/**
 * Describes the message group.v1.CreateGroupRequest.
 * Use `create(CreateGroupRequestSchema)` to create a new message.
 */
export const CreateGroupRequestSchema: GenMessage<CreateGroupRequest, {jsonType: CreateGroupRequestJson}> = /*@__PURE__*/
  messageDesc(file_group_v1_group, 2);

/**
 * @generated from message group.v1.GroupSummary
 */
export type GroupSummary = Message<"group.v1.GroupSummary"> & {
  /**
   * @generated from field: group.v1.Group group = 1;
   */
  group?: Group | undefined;

  /**
   * @generated from field: int32 member_count = 2;
   */
  memberCount: number;

  /**
   * The calling user's net position in the group.
   *
   * @generated from field: int32 your_net_cents = 3;
   */
  yourNetCents: number;
};

/**
 * @generated from message group.v1.GroupSummary
 */
export type GroupSummaryJson = {
  /**
   * @generated from field: group.v1.Group group = 1;
   */
  group?: GroupJson;

  /**
   * @generated from field: int32 member_count = 2;
   */
  memberCount?: number;

  /**
   * The calling user's net position in the group.
   *
   * @generated from field: int32 your_net_cents = 3;
   */
  yourNetCents?: number;
};

/**
 * Describes the message group.v1.GroupSummary.
 * Use `create(GroupSummarySchema)` to create a new message.
 */
export const GroupSummarySchema: GenMessage<GroupSummary, {jsonType: GroupSummaryJson}> = /*@__PURE__*/
  messageDesc(file_group_v1_group, 3);

/**
 * @generated from message group.v1.ListGroupsResponse
 */
export type ListGroupsResponse = Message<"group.v1.ListGroupsResponse"> & {
  /**
   * @generated from field: repeated group.v1.GroupSummary groups = 1;
   */
  groups: GroupSummary[];
};

/**
 * @generated from message group.v1.ListGroupsResponse
 */
export type ListGroupsResponseJson = {
  /**
   * @generated from field: repeated group.v1.GroupSummary groups = 1;
   */
  groups?: GroupSummaryJson[];
};

/**
 * Describes the message group.v1.ListGroupsResponse.
 * Use `create(ListGroupsResponseSchema)` to create a new message.
 */
export const ListGroupsResponseSchema: GenMessage<ListGroupsResponse, {jsonType: ListGroupsResponseJson}> = /*@__PURE__*/
  messageDesc(file_group_v1_group, 4);

/**
 * @generated from message group.v1.GetGroupRequest
 */
export type GetGroupRequest = Message<"group.v1.GetGroupRequest"> & {
  /**
   * @generated from field: string group_id = 1;
   */
  groupId: string;
};

/**
 * @generated from message group.v1.GetGroupRequest
 */
export type GetGroupRequestJson = {
  /**
   * @generated from field: string group_id = 1;
   */
  groupId?: string;
};

/**
 * Describes the message group.v1.GetGroupRequest.
 * Use `create(GetGroupRequestSchema)` to create a new message.
 */
export const GetGroupRequestSchema: GenMessage<GetGroupRequest, {jsonType: GetGroupRequestJson}> = /*@__PURE__*/
  messageDesc(file_group_v1_group, 5);

/**
 * @generated from message group.v1.AddMemberRequest
 */
export type AddMemberRequest = Message<"group.v1.AddMemberRequest"> & {
  /**
   * @generated from field: string group_id = 1;
   */
  groupId: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * optional display name for shadow users
   *
   * @generated from field: string name = 3;
   */
  name: string;
};

/**
 * @generated from message group.v1.AddMemberRequest
 */
export type AddMemberRequestJson = {
  /**
   * @generated from field: string group_id = 1;
   */
  groupId?: string;

  /**
   * @generated from field: string email = 2;
   */
  email?: string;

  /**
   * optional display name for shadow users
   *
   * @generated from field: string name = 3;
   */
  name?: string;
};

/**
 * Describes the message group.v1.AddMemberRequest.
 * Use `create(AddMemberRequestSchema)` to create a new message.
 */
export const AddMemberRequestSchema: GenMessage<AddMemberRequest, {jsonType: AddMemberRequestJson}> = /*@__PURE__*/
  messageDesc(file_group_v1_group, 6);

/**
 * @generated from message group.v1.RemoveMemberRequest
 */
export type RemoveMemberRequest = Message<"group.v1.RemoveMemberRequest"> & {
  /**
   * @generated from field: string group_id = 1;
   */
  groupId: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;
};

/**
 * @generated from message group.v1.RemoveMemberRequest
 */
export type RemoveMemberRequestJson = {
  /**
   * @generated from field: string group_id = 1;
   */
  groupId?: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId?: string;
};

/**
 * Describes the message group.v1.RemoveMemberRequest.
 * Use `create(RemoveMemberRequestSchema)` to create a new message.
 */
export const RemoveMemberRequestSchema: GenMessage<RemoveMemberRequest, {jsonType: RemoveMemberRequestJson}> = /*@__PURE__*/
  messageDesc(file_group_v1_group, 7);

/**
 * @generated from service group.v1.GroupService
 */
export const GroupService: GenService<{
  /**
   * @generated from rpc group.v1.GroupService.CreateGroup
   */
  createGroup: {
    methodKind: "unary";
    input: typeof CreateGroupRequestSchema;
    output: typeof GroupSchema;
  },
  /**
   * @generated from rpc group.v1.GroupService.ListGroups
   */
  listGroups: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof ListGroupsResponseSchema;
  },
  /**
   * @generated from rpc group.v1.GroupService.GetGroup
   */
  getGroup: {
    methodKind: "unary";
    input: typeof GetGroupRequestSchema;
    output: typeof GroupSchema;
  },
  /**
   * Adds a member by email. If no account exists a shadow user is created
   * (claimable later by signing up with that email).
   *
   * @generated from rpc group.v1.GroupService.AddMember
   */
  addMember: {
    methodKind: "unary";
    input: typeof AddMemberRequestSchema;
    output: typeof MemberSchema;
  },
  /**
   * @generated from rpc group.v1.GroupService.RemoveMember
   */
  removeMember: {
    methodKind: "unary";
    input: typeof RemoveMemberRequestSchema;
    output: typeof EmptySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_group_v1_group, 0);

